package com.bezkoder.springjwt.models;

public enum ERole {
  ROLE_USER,
  //ROLE_MODERATOR,
  ROLE_ADMIN,
  ROLE_RECRUITER,
  ROLE_INTERVIEWER, //TODO REMOVE
  ROLE_SALES,
  ROLE_TECH,
  ROLE_AC_COORDINATOR,
  ROLE_SUPER_RECRUITER,
  ROLE_CANDIDATE
}
